version: "3.7"

services:
    app:
        restart: always
        build:
            context: .
            dockerfile: app/Dockerfile
        container_name: change-maker-backend
        links:
            - db
        depends_on:
            - db
        volumes:
            - ./app:/app
        ports:
            - "8080:8080"
        environment:
            - PYTHONUNBUFFERED=1
        env_file: 
            - app.env
    db:
        image: mongo
        container_name: change_maker_db
        volumes:
            - ~/data/db:/data/db
        ports:
            - "27017:27017"